# Test against the latest version of this Node.js version
environment:
  matrix:
    - nodejs_version: "4"
      webpack_version: "1"
      babel_loader_version: "6"
    - nodejs_version: "6"
      webpack_version: "2"
      babel_loader_version: "7"
    - nodejs_version: "7"
      webpack_version: "2"
      babel_loader_version: "7"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm install webpack@%webpack_version% babel-loader@%babel_loader_version%

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - dir node_modules\.bin
  - npm test

# Don't actually build.
build_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run a build (node 4/webpack 1 will test with the build)
  - npm run build
